Use the following code for the questions below:

In [1]:
import numpy as np

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [2]:
negatives = a < 0
print(negatives)
negatives.sum()

[False False False False  True  True False False False  True False  True]


4

2. How many positive numbers are there?

In [3]:
positives = a > 0
print(positives)
positives.sum()

[ True  True  True  True False False False False False False  True False]


5

3. How many even positive numbers are there?

In [4]:
positive_evens = (a > 0) & (a % 2 == 0)
positive_evens.sum()

3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [62]:
array_plus_three = a + 3
print(array_plus_three)
array_plus_three = array_plus_three > 0
print(array_plus_three)
array_plus_three.sum()

[ 4  5  6  7  8  9 10 11 12 13]
[ True  True  True  True  True  True  True  True  True  True]


10

5. If you squared each number, what would the new mean and standard deviation be?

In [6]:
squared_array = a ** 2
print(squared_array)
print(squared_array.mean())
print(squared_array.std())

[ 16 100 144 529   4   1   0   0   0  36   9  49]
74.0
144.0243035046516


6. A common statistical operation on a dataset is centering. This means to adjust the data such that the center of the data is at 0. This is done by subtracting the mean from each data point. Center the data set.

In [7]:
mean = a.mean()
print(mean)
mean_array = a - mean
print(mean_array)

3.0
[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


7. Calculate the z-score for each data point. Recall that the z-score is given by:

$Z = \begin{array}{cc} \underline{x - \mu}  \\  \sigma \end{array}$


In [8]:
sigma = a.std()
print(sigma)

8.06225774829855


In [9]:
z_score = mean_array / sigma
print(z_score)

[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


8. Copy the setup and exercise directions from More Numpy Practice into your 4.8.3_numpy_exercises.py and add your solutions.

In [10]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [11]:
a = np.array(a)
sum_of_a = a.sum()
print(sum_of_a)

55


Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [12]:
min_of_a = a.min()
print(min_of_a)

1


Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [13]:
max_of_a = a.max()
print(max_of_a)

10


Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [14]:
mean_of_a = a.mean()
print(mean_of_a)

5.5


Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [15]:
product_of_a = a.prod()
print(product_of_a)

3628800


Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [16]:
squares_of_a = a * a
print(squares_of_a)

[  1   4   9  16  25  36  49  64  81 100]


Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [17]:
odds_in_a = a[a % 2 != 0]
print(odds_in_a)

[1 3 5 7 9]


Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [18]:
evens_in_a = a[a % 2 == 0]
print(evens_in_a)

[ 2  4  6  8 10]


Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [19]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [20]:
b = np.array(b)
sum_of_b = b.sum()
print(sum_of_b)

33


Exercise 2 - refactor the following to use numpy. 

In [21]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [22]:
min_of_b = b.min()
print(min_of_b)

3


Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [23]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [24]:
max_of_b = b.max()
print(max_of_b)

8


Exercise 4 - refactor the following using numpy to find the mean of b

In [25]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [26]:
mean_of_b = b.mean()
print(mean_of_b)

5.5


Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [27]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [28]:
product_of_b = b.prod()
print(product_of_b)

20160


Exercise 6 - refactor the following to use numpy to find the list of squares

In [29]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [30]:
squares_of_b = b.flatten() ** 2
print(squares_of_b)

[ 9 16 25 36 49 64]


Exercise 7 - refactor using numpy to determine the odds_in_b

In [31]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [32]:
odds_in_b = b[b % 2 != 0]
print(odds_in_b)

[3 5 7]


Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [33]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [34]:
evens_in_b = b[b % 2 == 0]
print(evens_in_b)

[4 6 8]


Exercise 9 - print out the shape of the array b.

In [35]:
np.shape(b)

(2, 3)

Exercise 10 - transpose the array b.

In [36]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [37]:
b.flatten()

array([3, 4, 5, 6, 7, 8])

Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [38]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [39]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

Exercise 1 - Find the min, max, sum, and product of c.

In [40]:
c = np.array(c)
print('min of c: {}'.format(c.min()))
print('max of c: {}'.format(c.max()))
print('sum of c: {}'.format(c.sum()))
print('product of c: {}'.format(c.prod()))

min of c: 1
max of c: 9
sum of c: 45
product of c: 362880


Exercise 2 - Determine the standard deviation of c.

In [41]:
print('standard deviation of c: {}'.format(c.std()))

standard deviation of c: 2.581988897471611


Exercise 3 - Determine the variance of c.

In [42]:
print('variance of c: {}'.format(c.var()))

variance of c: 6.666666666666667


Exercise 4 - Print out the shape of the array c

In [43]:
print('shape of c: {}'.format(np.shape(c)))

shape of c: (3, 3)


Exercise 5 - Transpose c and print out transposed result.

In [44]:
print('transpose of c: {}'.format(np.transpose(c)))

transpose of c: [[1 4 7]
 [2 5 8]
 [3 6 9]]


Exercise 6 - Get the dot product of the array c with c. 

In [45]:
print('dot product of c: {}'.format(np.dot(c, c)))

dot product of c: [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [46]:
print('sum of c * c transposed: {}'.format((c * np.transpose(c)).sum()))

sum of c * c transposed: 261


Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [47]:
print('product of c * c transposed: {}'.format((c * np.transpose(c)).prod().sum()))

product of c * c transposed: 131681894400


In [48]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

Exercise 1 - Find the sine of all the numbers in d

In [49]:
d = np.array(d)
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

Exercise 2 - Find the cosine of all the numbers in d

In [50]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

Exercise 3 - Find the tangent of all the numbers in d

In [51]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

Exercise 4 - Find all the negative numbers in d

In [52]:
d[d < 0]

array([-90, -30, -45, -45])

Exercise 5 - Find all the positive numbers in d

In [53]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

Exercise 6 - Return an array of only the unique numbers in d

In [54]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

Exercise 7 - Determine how many unique numbers there are in d

In [55]:
np.size(np.unique(d))

11

Exercise 8 - Print out the shape of d.

In [56]:
np.shape(d)

(3, 6)

Exercise 9 - Transpose and then print out the shape of d

In [57]:
np.shape(d.transpose())

(6, 3)

Exercise 10 - Reshape d into an array of 9 x 2

In [58]:
d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])